### ISSUE TITLE
`cmdk-sv` compiled shorthand store methods break in `svelte@5.0.0-next.55+`

### ISSUE THREAD

**Issue by ndom91** [huntabyte/cmdk-sv#58]
Seems that Svelte 5 compiled output of `cmdk-sv` is broken as of `next.55` :( 

Looks like the change that broke things was introduced here: https://github.com/sveltejs/svelte/pull/10477

I ran into this and while researching noticed someone else had already posted an issue related to this in the [svelte repo](https://github.com/sveltejs/svelte/issues/10492). Copying their output below:

### Repro

1. Install `svelte@5.0.0-next.55`

2. Attempt to use simple `cmdk-sv` example:
```svelte
<script lang="ts">
	import { Command } from 'cmdk-sv';
</script>

<Command.Root label="Command Menu">
	<Command.Input />
	<Command.List>
		<Command.Empty>No results found.</Command.Empty>

		<Command.Group heading="Letters">
			<Command.Item>a</Command.Item>
			<Command.Item>b</Command.Item>
			<Command.Separator />
			<Command.Item>c</Command.Item>
		</Command.Group>

		<Command.Item>Apple</Command.Item>
	</Command.List>
</Command.Root>
```

### Logs

```bash
✘ [ERROR] Invalid assignment target

    node_modules/.pnpm/cmdk-sv@0.0.13_svelte@5.0.0-next.55/node_modules/cmdk-sv/dist/cmdk/components/Command.svelte:82:30:
      82 │       $.mutate_store(stateStore, $.untrack($stateStore).value() = ...
         ╵                                  ^

9:12:20 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/cmdk-sv@0.0.13_svelte@5.0.0-next.55/node_modules/cmdk-sv/dist/cmdk/components/Command.svelte:82:30: ERROR: Invalid assignment target
    at failureErrorWithLog (/home/httpswwwsveltelabdev-dcnb/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1641:15)
    at eval (/home/httpswwwsveltelabdev-dcnb/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1049:25)
    at eval (/home/httpswwwsveltelabdev-dcnb/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1517:9)
```

CC: @zhihengGet

**Comment by huntabyte** [comment]
Related: #10359 - we can't officially support anything Svelte 5 until its stable.

**Comment by ndom91** [comment]
Fyi, I don't know if something old is cached, but it seems to be working again for me under `next.64`.
